#!/bin/bash

echo "dependecies-ubuntu start"

CODENAME="$(cat /etc/os-release | grep UBUNTU_CODENAME | cut -d = -f 2)"

sudo add-apt-repository universe
sudo add-apt-repository multiverse
sudo add-apt-repository restricted
sudo apt-get update

sudo apt install -y software-properties-common
sudo apt install -y ubuntu-restricted-addons
sudo apt install -y curl
sudo apt install -y rofi
sudo apt install -y rxvt-unicode
sudo apt install -y vlc
sudo apt install -y synaptic
sudo apt install -y python3-pip
sudo apt install -y google-chrome-stable 
sudo apt install -y build-essential libssl-dev libffi-dev python3-dev
sudo apt install -y awscli
sudo apt install -y neofetch
sudo apt install -y zsh 
sudo apt install -y vim 
sudo apt install -y tmux 
sudo apt install -y lutris
sudo apt install -y nautilus-dropbox
sudo apt install -y discord
sudo apt install -y thefuck
sudo apt install -y python3-tk
sudo apt install -y fonts-powerline
sudo apt install -y polybar
sudo apt install -y kmix
sudo apt install -y pasystray
sudo apt install -y xclip
sudo apt install -y s3ql
sudo apt install -y feh
sudo apt install -y eog
sudo apt install -y xbindkeys xsel xdotool
sudo apt install -y libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386
sudo apt install -y indent


if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
  echo "Installing Vundle"
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi


./scripts/install/install-ohmyzsh

#nvm
if [ ! -d ~/.nvm ]; then
  echo "Installing node version manager"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  nvm install node
fi


HAS_SPEED_RICER=$(apt-cache policy | grep 'speed-ricer')
if [ "$HAS_SPEED_RICER" == "" ]; then
  sudo add-apt-repository ppa:kgilmer/speed-ricer
  sudo apt-get update
  sudo apt-get install i3-gaps-wm
fi

#i3 topbar
if [ ! -f "$(which bumblebee-status)" ]; then
  echo "Installing bumblebee-status"
  pip3 install --user bumblebee-status
fi

./scripts/install/install-wine
./scripts/install/install-joplin
./scripts/install/install-bitwarden

echo "dependecies-ubuntu end"
