#!/bin/bash

echo "dependecies-ubuntu start"

CODENAME="$(cat /etc/os-release | grep UBUNTU_CODENAME | cut -d = -f 2)"

sudo add-apt-repository universe
sudo add-apt-repository multiverse
sudo add-apt-repository restricted
sudo apt-get update

sudo apt install -y software-properties-common
sudo apt install -y ubuntu-restricted-addons
sudo apt install -y vlc
sudo apt install -y synaptic
sudo apt install -y python3-pip
sudo apt install -y google-chrome-stable 
sudo apt install -y build-essential libssl-dev libffi-dev python3-dev
sudo apt install -y awscli
sudo apt install -y neofetch
sudo apt install -y zsh 
sudo apt install -y vim 
sudo apt install -y tmux 
#sudo apt install -y steam #??
sudo apt install -y lutris
sudo apt install -y nautilus-dropbox
sudo apt install -y discord

#android studio deps
sudo apt install -y libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386


sudo snap install slack


if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
  echo "Installing Vundle"
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi


#ohmyzsh
if [ ! -d ~/.oh-my-zsh ]; then
  echo "Installing oh my zsh"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

#nvm
if [ ! -d ~/.nvm ]; then
  echo "Installing node version manager"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  nvm install node
fi


HAS_SPEED_RICER=$(apt-cache policy | grep 'speed-ricer')
if [ "$HAS_SPEED_RICER" == "" ]; then
  sudo add-apt-repository ppa:kgilmer/speed-ricer
  sudo apt-get update
  sudo apt-get install i3-gaps-wm
fi

#wine
HAS_WINEHQ=$(apt-cache policy | grep 'dl.winehq.org')
if [ "$HAS_WINEHQ" == "" ]; then
  echo "Installing Wine"
  sudo dpkg --add-architecture i386
  wget -O /tmp/winehq.key https://dl.winehq.org/wine-builds/winehq.key
  sudo apt-key add /tmp/winehq.key
  sudo add-apt-repository "deb https://dl.winehq.org/wine-builds/ubuntu/ $CODENAME main"
  sudo apt update
  sudo apt install --install-recommends winehq-stable -y
fi


#i3 topbar
if [ ! -f "$(which bumblebee-status)" ]; then
  echo "Installing bumblebee-status"
  pip3 install --user bumblebee-status
fi


#Joplin 
if [ ! -d ~/.joplin ]; then
  wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
fi


#Bitwarden
if [ ! -d ~/.config/Bitwarden ]; then
  sudo snap install bitwarden
fi

#Microsoft Teams
if [ ! -d ~/.config/teams ]; then
  wget --output-document=/tmp/teams.deb https://go.microsoft.com/fwlink/p/\?linkid\=2112886\&clcid\=0x409\&culture\=en-us\&country\=us
  sudo dpkg -i /tmp/teams.deb
fi



echo "dependecies-ubuntu end"
